/**
 * Auto-generated types from PocketBase
 * 
 * To generate these types, run:
 *   pnpm --filter services typegen
 * 
 * This requires a running PocketBase instance at http://127.0.0.1:8090
 * 
 * NOTE: This file will be overwritten when types are generated.
 * For now, it serves as a placeholder.
 */

// Placeholder - will be auto-generated by pocketbase-typegen
export type PocketBaseSchema = Record<string, unknown>;
